# Generated by Django 6.0.2 on 2026-02-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='api_questio_status_68ee14_idx',
            old_name='api_questio_status_bf3660_idx',
        ),
    ]
