# Generated by Django 6.0.2 on 2026-02-16 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_abusereport'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first_useful_answer_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('account_created', 'Account Created'), ('question_created', 'Question Created'), ('answer_created', 'Answer Created'), ('first_answer_on_question', 'First Answer On Question'), ('useful_answer_consumed', 'Useful Answer Consumed')], max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_events', to='api.answer')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_events', to='core.profile')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_events', to='api.question')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='api_metrice_event_t_d7caeb_idx'), models.Index(fields=['profile', '-created_at'], name='api_metrice_profile_3969b9_idx')],
            },
        ),
    ]
