# Generated by Django 6.0.2 on 2026-02-17 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_first_useful_answer_seen_at_metricevent'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_setup_tokens', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
