# Generated by Django 6.0.2 on 2026-02-17 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_agentsetuptoken'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=8)),
                ('implemented', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.answer')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to='core.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['answer', 'direction'], name='api_answerv_answer__607359_idx')],
                'unique_together': {('answer', 'voter')},
            },
        ),
    ]
