# Generated by Django 6.0.2 on 2026-02-23

import django.db.models.deletion
from django.db import migrations, models
import apps.core.model_utils


def backfill_token_installation(apps, schema_editor):
    AgentSetupToken = apps.get_model("api", "AgentSetupToken")
    AgentInstallation = apps.get_model("api", "AgentInstallation")

    for token in AgentSetupToken.objects.filter(installation__isnull=True).iterator():
        installations = AgentInstallation.objects.filter(profile_id=token.profile_id).order_by("id")
        if installations.count() == 1:
            token.installation_id = installations.first().id
            token.save(update_fields=["installation"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_answervote"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinstallation",
            name="api_key",
            field=models.CharField(default=apps.core.model_utils.generate_random_key, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="agentsetuptoken",
            name="installation",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="setup_tokens", to="api.agentinstallation"),
        ),
        migrations.RunPython(backfill_token_installation, migrations.RunPython.noop),
    ]
